apiVersion: v1
kind: ServiceAccount
metadata:
  name: kube-rbac-proxy-client
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: kube-rbac-proxy-client
spec:
  selector:
    matchLabels:
      name: kube-rbac-proxy-client
  template:
    metadata:
      name: kube-rbac-proxy-client
      labels:
        name: kube-rbac-proxy-client
    spec:
      serviceAccountName: kube-rbac-proxy-client
      containers:
      - name: krp-curl
        image: quay.io/brancz/krp-curl:v0.0.1
        command: ["/bin/sleep", "3600"]
